"""batch4_medium_features

Revision ID: 38426e7f183f
Revises: 08b9432dba99
Create Date: 2026-03-31 13:37:15.207001

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "38426e7f183f"
down_revision: Union[str, None] = "08b9432dba99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metric_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=True),
        sa.Column("cpu_percent", sa.Float(), nullable=False),
        sa.Column("memory_mb", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("metric_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_metric_snapshots_server_id"), ["server_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_metric_snapshots_timestamp"), ["timestamp"], unique=False
        )

    with op.batch_alter_table("servers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("max_backups", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("rcon_enabled", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("rcon_port", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("rcon_password", sa.String(length=255), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("servers", schema=None) as batch_op:
        batch_op.drop_column("rcon_password")
        batch_op.drop_column("rcon_port")
        batch_op.drop_column("rcon_enabled")
        batch_op.drop_column("max_backups")

    with op.batch_alter_table("metric_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_metric_snapshots_timestamp"))
        batch_op.drop_index(batch_op.f("ix_metric_snapshots_server_id"))

    op.drop_table("metric_snapshots")
    # ### end Alembic commands ###
