"""Predefined server configuration templates for quick setup."""

TEMPLATES = [
    {
        "id": "mc_vanilla_survival",
        "name": "Minecraft Vanilla Survival",
        "server_type": "minecraft_java",
        "loader": "",
        "min_memory": 1024,
        "max_memory": 2048,
        "description": "Standard Minecraft survival server with default settings.",
    },
    {
        "id": "mc_paper_survival",
        "name": "Paper Survival (Optimized)",
        "server_type": "minecraft_java",
        "loader": "paper",
        "min_memory": 2048,
        "max_memory": 4096,
        "description": "Performance-optimized Paper server for survival gameplay.",
    },
    {
        "id": "mc_fabric_modded",
        "name": "Fabric Modded",
        "server_type": "minecraft_java",
        "loader": "fabric",
        "min_memory": 4096,
        "max_memory": 8192,
        "description": "Fabric server for modded Minecraft.",
    },
    {
        "id": "mc_forge_modded",
        "name": "Forge Modded",
        "server_type": "minecraft_java",
        "loader": "forge",
        "min_memory": 4096,
        "max_memory": 8192,
        "description": "Forge server for modded Minecraft.",
    },
    {
        "id": "mc_neoforge_modded",
        "name": "NeoForge Modded",
        "server_type": "minecraft_java",
        "loader": "neoforge",
        "min_memory": 4096,
        "max_memory": 8192,
        "description": "NeoForge server for modern modded Minecraft.",
    },
    {
        "id": "mc_quilt_modded",
        "name": "Quilt Modded",
        "server_type": "minecraft_java",
        "loader": "quilt",
        "min_memory": 4096,
        "max_memory": 8192,
        "description": "Quilt server for modded Minecraft.",
    },
    {
        "id": "mc_bedrock",
        "name": "Minecraft Bedrock",
        "server_type": "minecraft_bedrock",
        "loader": "",
        "min_memory": 1024,
        "max_memory": 2048,
        "description": "Bedrock Edition dedicated server.",
    },
    # Steam Server Presets
    {
        "id": "steam_cs2",
        "name": "Counter-Strike 2",
        "server_type": "steam",
        "loader": "",
        "min_memory": 1024,
        "max_memory": 2048,
        "description": "CS2 dedicated server via SteamCMD (App ID 730).",
        "steam_app_id": "730",
        "port": 27015,
    },
    {
        "id": "steam_valheim",
        "name": "Valheim Dedicated",
        "server_type": "steam",
        "loader": "",
        "min_memory": 2048,
        "max_memory": 4096,
        "description": "Valheim dedicated server via SteamCMD (App ID 896660).",
        "steam_app_id": "896660",
        "port": 2456,
    },
    {
        "id": "steam_rust",
        "name": "Rust Dedicated",
        "server_type": "steam",
        "loader": "",
        "min_memory": 4096,
        "max_memory": 8192,
        "description": "Rust dedicated server via SteamCMD (App ID 258550).",
        "steam_app_id": "258550",
        "port": 28015,
    },
    {
        "id": "steam_palworld",
        "name": "Palworld Dedicated",
        "server_type": "steam",
        "loader": "",
        "min_memory": 4096,
        "max_memory": 8192,
        "description": "Palworld dedicated server via SteamCMD (App ID 2394010).",
        "steam_app_id": "2394010",
        "port": 8211,
    },
    {
        "id": "steam_7dtd",
        "name": "7 Days to Die",
        "server_type": "steam",
        "loader": "",
        "min_memory": 4096,
        "max_memory": 8192,
        "description": "7 Days to Die dedicated server via SteamCMD (App ID 294420).",
        "steam_app_id": "294420",
        "port": 26900,
    },
    {
        "id": "steam_satisfactory",
        "name": "Satisfactory Dedicated",
        "server_type": "steam",
        "loader": "",
        "min_memory": 4096,
        "max_memory": 8192,
        "description": "Satisfactory dedicated server via SteamCMD (App ID 1690800).",
        "steam_app_id": "1690800",
        "port": 7777,
    },
]


def get_templates() -> list[dict]:
    return TEMPLATES


def get_template(template_id: str) -> dict | None:
    return next((t for t in TEMPLATES if t["id"] == template_id), None)
