"""add_docker_isolation_fields

Revision ID: a1c577628359
Revises: fb5cbe13910d
Create Date: 2026-03-31 14:20:10.093023

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a1c577628359"
down_revision: Union[str, None] = "fb5cbe13910d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("servers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("container_id", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(sa.Column("cpu_limit", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("memory_limit_mb", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("servers", schema=None) as batch_op:
        batch_op.drop_column("memory_limit_mb")
        batch_op.drop_column("cpu_limit")
        batch_op.drop_column("container_id")

    # ### end Alembic commands ###
