"""initial schema

Revision ID: 540b8ead69ca
Revises:
Create Date: 2026-03-31 12:27:48.185750

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "540b8ead69ca"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "servers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "server_type",
            sa.Enum("MINECRAFT_JAVA", "MINECRAFT_BEDROCK", "STEAM", name="servertype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "STOPPED",
                "STARTING",
                "RUNNING",
                "STOPPING",
                "CRASHED",
                name="serverstatus",
            ),
            nullable=False,
        ),
        sa.Column("path", sa.String(length=500), nullable=False),
        sa.Column("executable", sa.String(length=500), nullable=False),
        sa.Column("start_command", sa.Text(), nullable=False),
        sa.Column("java_path", sa.String(length=500), nullable=False),
        sa.Column("min_memory", sa.Integer(), nullable=False),
        sa.Column("max_memory", sa.Integer(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("auto_start", sa.Boolean(), nullable=False),
        sa.Column("auto_update_mods", sa.Boolean(), nullable=False),
        sa.Column("steam_app_id", sa.String(length=20), nullable=True),
        sa.Column("mc_version", sa.String(length=20), nullable=True),
        sa.Column("loader", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mods",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("project_id", sa.String(length=100), nullable=False),
        sa.Column("version_id", sa.String(length=100), nullable=True),
        sa.Column("installed_version", sa.String(length=100), nullable=True),
        sa.Column("latest_version", sa.String(length=100), nullable=True),
        sa.Column("file_name", sa.String(length=500), nullable=True),
        sa.Column("download_url", sa.Text(), nullable=True),
        sa.Column("auto_update", sa.Boolean(), nullable=False),
        sa.Column("update_available", sa.Boolean(), nullable=False),
        sa.Column("last_checked", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mods")
    op.drop_table("servers")
    # ### end Alembic commands ###
